version: "3.9"
services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    # Expose port 3000.
    # ports:
    #   - "3000:3000"
    # depends_on:
    #   - database
    stdin_open: true
    tty: true
    environment:
      DATABASE_HOST: database
#   database:
#     image: postgres:13.3
#     ports:
#       - "5432:5432"
#     restart: always
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: root
# volumes:
#   pg_data:
